### ISSUE TITLE
'Quad' object has no attribute 'tl'

### ISSUE THREAD

**Issue by IronK77** [pymupdf/RAG#90] opened 2024-07-29 03:15 UTC
Hi.

I am trying to use pymupdf4llm on google colab. The error 'Quad' object has no attribute 'tl' is on a specific pdf, but I can do it smoothly offline. I wonder what would be the related code. Not sure if it is related to the is_siginificant reporting, but maybe it is the same issue.

I am just checking the versions. I can do the job with 0.0.6-0.0.9, and the error is appeared in the recent 0.0.10.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-9-794bd8ecc0e3>](https://localhost:8080/#) in <cell line: 5>()
      3 file_name=path.split("/")[-1]
      4 path_full="/content/drive//MyDrive/eval/esg/"+file_name
----> 5 md_text = pymupdf4llm.to_markdown(path_full,write_images=False)
      6 path_o="/content/drive//MyDrive/eval/esg-md/"+regex.sub("pdf","md",file_name)
      7 pathlib.Path(path_o).write_bytes(md_text.encode())

2 frames
[/usr/local/lib/python3.10/dist-packages/pymupdf4llm/helpers/pymupdf_rag.py](https://localhost:8080/#) in is_significant(box, paths)
    204                     points.extend([r.tl, r.bl, r.br, r.tr, r.tl])
    205                 else:  # clockwise: area counts as negative
--> 206                     points.extend([r.tl, r.tr, r.br, r.bl, r.tl])
    207         area = poly_area(points)  # compute area of polygon
    208         if area < box_area:  # less than threshold: graphic is significant

**Comment by Stephen-S-H** [comment] 2024-07-29 03:53
I'm having the same issue on the occasional PDF. I'm doing a bit of testing and will let you know what I find.

**Comment by Stephen-S-H** [comment] 2024-07-29 04:08
The same issue is here:
https://github.com/pymupdf/RAG/issues/88

**Comment by Buckler89** [comment] 2024-07-29 10:27
I'm also having the same problem, but only with some PDFs. I haven't figured out the difference between a working PDF and one that doesn't work yet.

**Comment by itsomar278** [comment] 2024-08-22 12:53
Facing the same issue

**Comment by JorjMcKie** [comment] 2024-08-22 17:02
Fixed in v0.0.11.

**Closed by JorjMcKie** 2024-08-22 17:02 UTC
Labels: fix developed

**Comment by itsomar278** [comment] 2024-08-27 12:51
The same  PDF file ( 40 MB ) which triggered that exception now keeps running for hours with no extracted text 
I can provide the file if needed

**Comment by JorjMcKie** [comment] 2024-08-29 06:54
@itsomar278 - A number of reasons could lead to this behavior. We can certainly look at the file itself.
But as a first action, you can try the following.
Use PyMuPDF to help track down on which pages of that file the most time is spent. Use PyMuPDF to help you do this:
```python
import pymupdf4llm
import pymupdf
doc = pymupdf.open("input.pdf")
md = ""  # store markdown result here
for page in doc:
    md += pymupdf4llm.to_markdown(doc,
            pages=[page.number],  # deal with one page at a time
            hdr_info=False,  # ignore header tagging for now
            graphics_limit=2000,  # ignore pages with too many vector graphics
            )
    print(f"processed {page.number=}")  # show how far we are

# process created Markdown string
...
```

This can help you find out on which page a lot of time is spent.
There also is parameter `graphics_limit`, which lets you deal with timing problems caused by too many vector graphics. A typical reasonable limit is 5000 or even 2000 as shown above.

**Comment by JorjMcKie** [comment] 2024-08-29 12:47
Glad it worked for you!

**Comment by itsomar278** [comment] 2024-08-29 13:12
<div style="width:100%;height:0;padding-bottom:56%;position:relative;"><iframe src="https://giphy.com/embed/cuGIGsQGaVV6KUDZCA" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/nyit-college-new-york-tech-thisisyourplace-cuGIGsQGaVV6KUDZCA">via GIPHY</a></p>
